### ISSUE TITLE
Konwencja nazw

### ISSUE THREAD

**Issue by marcinlawnik** [akai-org/rekrutacja_2019#2]
Sugeruję w głównym katalogu podkatalogi z nazwą języka lowercase oddzielaną myślnikami - `python`, `ruby-on-rails`, a poziom niżej katalogi z zadaniami, ponazywane i opisujące jakoś zadanie - `tic-tac-toe`, `reverse-list`, `fizz-buzz`.

Dodatkowo zmieniłbym nazwę repo na `rekrutacja` - nie spodziewam się żeby zostały zużyte wszystkie taski, a przydadzą się na przysłość. Po sprawdzeniu zamierzam przenieść i zmodyfikować część tasków z poprzedniej rekrutacji.

**Comment by roertbb** [comment]
Good idea - mogę zająć się swoimi taskami. Optuję za zmigrowaniem taska Piotra - https://github.com/akai-org/task-frontend

**Comment by dwdzdc** [comment]
Spoko. Jak to się ma do #7? Daty i pod nimi jezyki, czy jezyki i pod nimi daty?

**Comment by marcinlawnik** [comment]
Jak dla mnie obojętnie, byle konsekwentnie. Chyba najpierw lata, skoro uczestnicy będą robić tylko aktualne zadania.

**Comment by marcinlawnik** [comment]
Zamykam, bo wdrożone.
