### ISSUE TITLE
Posortować zadania rekruracyjne na lata

### ISSUE THREAD

**Issue by marcinlawnik** [akai-org/rekrutacja_2019#7]
Utworzenie katalogów 2017, 2018, 2019, 2020?

**Comment by dwdzdc** [comment]
Przenieśmy ten problem do #2, bo można łatwo dwie sprawy na raz klepnąć

**Comment by dwdzdc** [comment]
Zamykam 

https://github.com/akai-org/rekrutacja/issues/2#issuecomment-930141782
